name: Publish

on:
  push:
    branches:
      - release

env:
  USE_HARD_LINKS: false

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v1

      - name: Install Node and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: yarn install --network-timeout 1000000 && npm install typescript -g

      - name: Publish releases
        run: |
          yarn postinstall
          yarn build
          yarn exec electron-builder -- --publish always --linux
